### PR TITLE
Add DPI Scaling Registry setting test

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@fjvallarino @tejohnso ready for review

### CODE REVIEW

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso derp. I should add a cleanup task that resets registry values.

**Comment by ahmedalsudani** [comment]
@fjvallarino @tejohnso Added

**Comment by fjvallarino** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
:+1: @tejohnso. Merging

**Comment by tejohnso** [comment]
:+1:

**Pull request merged**
