### PR TITLE
Automatically update tests

### PR DESCRIPTION
**Pull request by ahmedalsudani**
@tejohnso @fjvallarino this PR should make it possible to automatically update E2E tests.

The idea is:

- a github webhook calls `hostname/upgrade-e2e-tests` and sends a signature for authorization
- if authorization passes, and the push was to master, we restart the platform
- the startup script pulls the new version and restarts the server

Some caveats:

- we need to exclude configuration files like `displayid.txt` from revision control so they are not overwritten when we `git pull`
- the github webhooks will have to be set up with a secret key
- we do not install packages as part of startup. So if our dependencies change, it will still require manually running `npm i`

As part of this PR, I also moved our `rise-common-electron` dependency to master

### CODE REVIEW

**Comment by tejohnso** [comment]
@ahmedalsudani Looks good.  Assuming this was tested manually on windows and linux by calling the upgrade endpoint. :+1:

**Comment by ahmedalsudani** [comment]
@tejohnso sorry, I had to make a few modifications. 

Testing the changes out in production against Github, I realized there were two problems:

- the signature format Github sends contains the hash at the beginning. E.g. `"sha1=..."`
- on Windows, it was not launching because the script needed to be launched in the background.

So I fixed those two and had to import `background.jse` from launcher.

In the process, I changed the script files slightly so that they don't assume the e2e runner sits in the home directory.

**Comment by tejohnso** [comment]
:+1:

**Comment by ahmedalsudani** [comment]
@tejohnso merged with minor modification (the last commit)

**Pull request merged**
